[36m[2023-12-08 17:48:15 DEBUG] [cli:114][39m ###############################################################################
[36m[2023-12-08 17:48:15 DEBUG] [cli:115][39m Running command 'run'
[36m[2023-12-08 17:48:15 DEBUG] [cli:119][39m Using settings file '/root/.chaostoolkit/settings.yaml'
[36m[2023-12-08 17:48:17 DEBUG] [settings:30][39m The Chaos Toolkit settings file could not be found at '/root/.chaostoolkit/settings.yaml'.
[36m[2023-12-08 17:48:17 DEBUG] [__init__:445][39m No controls to apply on 'loader'
[36m[2023-12-08 17:48:17 DEBUG] [__init__:445][39m No controls to apply on 'loader'
[36m[2023-12-08 17:48:17 DEBUG] [caching:24][39m Building activity cache...
[36m[2023-12-08 17:48:17 DEBUG] [caching:35][39m Cached 9 activities
[32m[2023-12-08 17:48:17 INFO] [experiment:58][39m Validating the experiment's syntax
[36m[2023-12-08 17:48:17 DEBUG] [configuration:63][39m Loading configuration...
[36m[2023-12-08 17:48:17 DEBUG] [secret:78][39m Loading secrets...
[36m[2023-12-08 17:48:17 DEBUG] [secret:103][39m Done loading secrets
[32m[2023-12-08 17:48:17 INFO] [experiment:109][39m Experiment looks valid
[36m[2023-12-08 17:48:17 DEBUG] [caching:42][39m Clearing activities cache
[36m[2023-12-08 17:48:17 DEBUG] [cli:314][39m Runtime strategies: hypothesis - before-method-only / rollbacks - default
[36m[2023-12-08 17:48:17 DEBUG] [caching:24][39m Building activity cache...
[36m[2023-12-08 17:48:17 DEBUG] [caching:35][39m Cached 9 activities
[36m[2023-12-08 17:48:17 DEBUG] [configuration:63][39m Loading configuration...
[36m[2023-12-08 17:48:17 DEBUG] [secret:78][39m Loading secrets...
[36m[2023-12-08 17:48:17 DEBUG] [secret:103][39m Done loading secrets
[36m[2023-12-08 17:48:17 DEBUG] [configuration:160][39m Loading dynamic configuration...
[32m[2023-12-08 17:48:17 INFO] [run:369][39m Running experiment: Chaos Offline ML Training Server Experiment
[36m[2023-12-08 17:48:17 DEBUG] [__init__:59][39m Initializing controls
[36m[2023-12-08 17:48:17 DEBUG] [__init__:68][39m Initializing control 'Change CHAOS_TYPE env value to off-interface'
[32m[2023-12-08 17:48:17 INFO] [run:396][39m Steady-state strategy: before-method-only
[32m[2023-12-08 17:48:17 INFO] [run:400][39m Rollbacks strategy: default
[36m[2023-12-08 17:48:17 DEBUG] [__init__:445][39m No controls to apply on 'experiment'
[36m[2023-12-08 17:48:17 DEBUG] [run:563][39m Running steady-state hypothesis before the method
[32m[2023-12-08 17:48:17 INFO] [hypothesis:186][39m Steady state hypothesis: Make sure that load testing has been done & able to prompt every types to server
[36m[2023-12-08 17:48:17 DEBUG] [__init__:445][39m No controls to apply on 'hypothesis'
[36m[2023-12-08 17:48:17 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-12-08 17:48:17 INFO] [activity:215][39m Probe: Normal load success rate testing log must exists
[36m[2023-12-08 17:48:17 DEBUG] [python:33][39m Activity 'Normal load success rate testing log must exists' loaded from '/usr/lib/python3.10/genericpath.py'
[36m[2023-12-08 17:48:17 DEBUG] [activity:237][39m   => succeeded with 'True'
[36m[2023-12-08 17:48:17 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[36m[2023-12-08 17:48:17 DEBUG] [hypothesis:228][39m allowed tolerance is True
[36m[2023-12-08 17:48:17 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-12-08 17:48:17 INFO] [activity:215][39m Probe: Normal load testing log must exists
[36m[2023-12-08 17:48:17 DEBUG] [python:33][39m Activity 'Normal load testing log must exists' loaded from '/usr/lib/python3.10/genericpath.py'
[36m[2023-12-08 17:48:17 DEBUG] [activity:237][39m   => succeeded with 'True'
[36m[2023-12-08 17:48:17 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[36m[2023-12-08 17:48:17 DEBUG] [hypothesis:228][39m allowed tolerance is True
[36m[2023-12-08 17:48:17 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-12-08 17:48:17 INFO] [activity:215][39m Probe: We can request text
[36m[2023-12-08 17:48:18 DEBUG] [activity:237][39m   => succeeded with '{'status': 200, 'headers': {'date': 'Fri, 08 Dec 2023 17:48:17 GMT', 'server': 'uvicorn', 'content-length': '31', 'content-type': 'application/json'}, 'body': {'error': False, 'response': None}}'
[36m[2023-12-08 17:48:18 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[36m[2023-12-08 17:48:18 DEBUG] [hypothesis:228][39m allowed tolerance is 200
[36m[2023-12-08 17:48:18 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-12-08 17:48:18 INFO] [activity:215][39m Probe: We can request image
[36m[2023-12-08 17:48:19 DEBUG] [activity:237][39m   => succeeded with '{'status': 200, 'headers': {'date': 'Fri, 08 Dec 2023 17:48:18 GMT', 'server': 'uvicorn', 'content-length': '31', 'content-type': 'application/json'}, 'body': {'error': False, 'response': None}}'
[36m[2023-12-08 17:48:19 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[36m[2023-12-08 17:48:19 DEBUG] [hypothesis:228][39m allowed tolerance is 200
[32m[2023-12-08 17:48:19 INFO] [hypothesis:238][39m Steady state hypothesis is met!
[36m[2023-12-08 17:48:19 DEBUG] [__init__:445][39m No controls to apply on 'hypothesis'
[32m[2023-12-08 17:48:19 INFO] [run:677][39m Playing your experiment's method now...
[36m[2023-12-08 17:48:19 DEBUG] [__init__:445][39m No controls to apply on 'method'
[36m[2023-12-08 17:48:19 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-12-08 17:48:19 INFO] [activity:215][39m Action: Turn off interface VM on Google Cloud Platform
[36m[2023-12-08 17:48:19 DEBUG] [process:52][39m Running: /usr/bin/gcloud compute instances stop --zone us-central1-a proxy-interaface
[36m[2023-12-08 17:49:25 DEBUG] [__init__:149][39m Data encoding detected as 'utf-8' with a confidence of 1.0
[36m[2023-12-08 17:49:25 DEBUG] [__init__:149][39m Data encoding detected as 'ascii' with a confidence of 1.0
[36m[2023-12-08 17:49:25 DEBUG] [activity:237][39m   => succeeded with '{'status': 0, 'stdout': '', 'stderr': 'Stopping instance(s) proxy-interaface...\n.................................................................................................................................................................................................................................................................................................................done.\nUpdated [https://compute.googleapis.com/compute/v1/projects/mlops-398205/zones/us-central1-a/instances/proxy-interaface].\n'}'
[36m[2023-12-08 17:49:25 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[36m[2023-12-08 17:49:25 DEBUG] [__init__:455][39m Applying before-control 'Change CHAOS_TYPE env value to off-interface' on 'activity'
[32m[2023-12-08 17:49:25 INFO] [activity:215][39m Action: Run load success rate testing
[36m[2023-12-08 17:49:25 DEBUG] [process:52][39m Running: /usr/bin/k6 run -o experimental-prometheus-rw load-successrate-testing.js
[36m[2023-12-08 17:50:45 DEBUG] [__init__:149][39m Data encoding detected as 'utf-8' with a confidence of 1.0
[36m[2023-12-08 17:50:45 DEBUG] [__init__:149][39m Data encoding detected as 'ascii' with a confidence of 1.0
[36m[2023-12-08 17:50:45 DEBUG] [activity:237][39m   => succeeded with '{'status': 0, 'stdout': '\n          /\\      |â€¾â€¾| /â€¾â€¾/   /â€¾â€¾/   \n     /\\  /  \\     |  |/  /   /  /    \n    /  \\/    \\    |     (   /   â€¾â€¾\\  \n   /          \\   |  |\\  \\ |  (â€¾)  | \n  / __________ \\  |__| \\__\\ \\_____/ .io\n\n  execution: local\n     script: load-successrate-testing.js\n     output: Prometheus remote write (http://localhost:9090/api/v1/write)\n\n  scenarios: (100.00%) 1 scenario, 1 max VUs, 1m0s max duration (incl. graceful stop):\n           * 1-user: 1 iterations for each of 1 VUs (maxDuration: 1m0s)\n\n\nrunning (0m01.0s), 1/1 VUs, 0 complete and 0 interrupted iterations\n1-user   [   0% ] 1 VUs  0m01.0s/1m0s  0/1 iters, 1 per VU\n\nrunning (0m02.0s), 1/1 VUs, 0 complete and 0 interrupted iterations\n1-user   [   0% ] 1 VUs  0m02.0s/1m0s  0/1 iters, 1 per VU\n\nrunning (0m03.0s), 1/1 VUs, 0 complete and 0 interrupted iterations\n1-user   [   0% ] 1 VUs  0m03.0s/1m0s  0/1 iters, 1 per VU\n\nrunning (0m04.0s), 1/1 VUs, 0 complete and 0 interrupted iterations\n1-user   [   0% ] 1 VUs  0m04.0s/1m0s  0/1 iters, 1 per VU\n\nrunning (0m05.0s), 1/1 VUs, 0 complete and 0 interrupted iterations\n1-user   [   0% ] 1 VUs  0m05.0s/1m0s  0/1 iters, 1 per VU\n\nrunning (0m06.0s), 1/1 VUs, 0 complete and 0 interrupted iterations\n1-user   [   0% ] 1 VUs  0m06.0s/1m0s  0/1 iters, 1 per VU\n\nrunning (0m07.0s), 1/1 VUs, 0 complete and 0 interrupted iterations\n1-user   [   0% ] 1 VUs  0m07.0s/1m0s  0/1 iters, 1 per VU\n\nrunning (0m08.0s), 1/1 VUs, 0 complete and 0 interrupted iterations\n1-user   [   0% ] 1 VUs  0m08.0s/1m0s  0/1 iters, 1 per VU\n\nrunning (0m09.0s), 1/1 VUs, 0 complete and 0 interrupted iterations\n1-user   [   0% ] 1 VUs  0m09.0s/1m0s  0/1 iters, 1 per VU\n\nrunning (0m10.0s), 1/1 VUs, 0 complete and 0 interrupted iterations\n1-user   [   0% ] 1 VUs  0m10.0s/1m0s  0/1 iters, 1 per VU\n\nrunning (0m11.0s), 1/1 VUs, 0 complete and 0 interrupted iterations\n1-user   [   0% ] 1 VUs  0m11.0s/1m0s  0/1 iters, 1 per VU\n\nrunning (0m12.0s), 1/1 VUs, 0 complete and 0 interrupted iterations\n1-user   [   0% ] 1 VUs  0m12.0s/1m0s  0/1 iters, 1 per VU\n\nrunning (0m13.0s), 1/1 VUs, 0 complete and 0 interrupted iterations\n1-user   [   0% ] 1 VUs  0m13.0s/1m0s  0/1 iters, 1 per VU\n\nrunning (0m14.0s), 1/1 VUs, 0 complete and 0 interrupted iterations\n1-user   [   0% ] 1 VUs  0m14.0s/1m0s  0/1 iters, 1 per VU\n\nrunning (0m15.0s), 1/1 VUs, 0 complete and 0 interrupted iterations\n1-user   [   0% ] 1 VUs  0m15.0s/1m0s  0/1 iters, 1 per VU\n\nrunning (0m16.0s), 1/1 VUs, 0 complete and 0 interrupted iterations\n1-user   [   0% ] 1 VUs  0m16.0s/1m0s  0/1 iters, 1 per VU\n\nrunning (0m17.0s), 1/1 VUs, 0 complete and 0 interrupted iterations\n1-user   [   0% ] 1 VUs  0m17.0s/1m0s  0/1 iters, 1 per VU\n\nrunning (0m18.0s), 1/1 VUs, 0 complete and 0 interrupted iterations\n1-user   [   0% ] 1 VUs  0m18.0s/1m0s  0/1 iters, 1 per VU\n\nrunning (0m19.0s), 1/1 VUs, 0 complete and 0 interrupted iterations\n1-user   [   0% ] 1 VUs  0m19.0s/1m0s  0/1 iters, 1 per VU\n\nrunning (0m20.0s), 1/1 VUs, 0 complete and 0 interrupted iterations\n1-user   [   0% ] 1 VUs  0m20.0s/1m0s  0/1 iters, 1 per VU\n\nrunning (0m21.0s), 1/1 VUs, 0 complete and 0 interrupted iterations\n1-user   [   0% ] 1 VUs  0m21.0s/1m0s  0/1 iters, 1 per VU\n\nrunning (0m22.0s), 1/1 VUs, 0 complete and 0 interrupted iterations\n1-user   [   0% ] 1 VUs  0m22.0s/1m0s  0/1 iters, 1 per VU\n\nrunning (0m23.0s), 1/1 VUs, 0 complete and 0 interrupted iterations\n1-user   [   0% ] 1 VUs  0m23.0s/1m0s  0/1 iters, 1 per VU\n\nrunning (0m24.0s), 1/1 VUs, 0 complete and 0 interrupted iterations\n1-user   [   0% ] 1 VUs  0m24.0s/1m0s  0/1 iters, 1 per VU\n\nrunning (0m25.0s), 1/1 VUs, 0 complete and 0 interrupted iterations\n1-user   [   0% ] 1 VUs  0m25.0s/1m0s  0/1 iters, 1 per VU\n\nrunning (0m26.0s), 1/1 VUs, 0 complete and 0 interrupted iterations\n1-user   [   0% ] 1 VUs  0m26.0s/1m0s  0/1 iters, 1 per VU\n\nrunning (0m27.0s), 1/1 VUs, 0 complete and 0 interrupted iterations\n1-user   [   0% ] 1 VUs  0m27.0s/1m0s  0/1 iters, 1 per VU\n\nrunning (0m28.0s), 1/1 VUs, 0 complete and 0 interrupted iterations\n1-user   [   0% ] 1 VUs  0m28.0s/1m0s  0/1 iters, 1 per VU\n\nrunning (0m29.0s), 1/1 VUs, 0 complete and 0 interrupted iterations\n1-user   [   0% ] 1 VUs  0m29.0s/1m0s  0/1 iters, 1 per VU\n\nrunning (0m30.0s), 1/1 VUs, 0 complete and 0 interrupted iterations\n1-user   [   0% ] 1 VUs  0m30.0s/1m0s  0/1 iters, 1 per VU\n\nrunning (0m31.0s), 1/1 VUs, 0 complete and 0 interrupted iterations\n1-user   [   0% ] 1 VUs  0m31.0s/1m0s  0/1 iters, 1 per VU\n\nrunning (0m32.0s), 1/1 VUs, 0 complete and 0 interrupted iterations\n1-user   [   0% ] 1 VUs  0m32.0s/1m0s  0/1 iters, 1 per VU\n\nrunning (0m33.0s), 1/1 VUs, 0 complete and 0 interrupted iterations\n1-user   [   0% ] 1 VUs  0m33.0s/1m0s  0/1 iters, 1 per VU\n\nrunning (0m34.0s), 1/1 VUs, 0 complete and 0 interrupted iterations\n1-user   [   0% ] 1 VUs  0m34.0s/1m0s  0/1 iters, 1 per VU\n\nrunning (0m35.0s), 1/1 VUs, 0 complete and 0 interrupted iterations\n1-user   [   0% ] 1 VUs  0m35.0s/1m0s  0/1 iters, 1 per VU\n\nrunning (0m36.0s), 1/1 VUs, 0 complete and 0 interrupted iterations\n1-user   [   0% ] 1 VUs  0m36.0s/1m0s  0/1 iters, 1 per VU\n\nrunning (0m37.0s), 1/1 VUs, 0 complete and 0 interrupted iterations\n1-user   [   0% ] 1 VUs  0m37.0s/1m0s  0/1 iters, 1 per VU\n\nrunning (0m38.0s), 1/1 VUs, 0 complete and 0 interrupted iterations\n1-user   [   0% ] 1 VUs  0m38.0s/1m0s  0/1 iters, 1 per VU\n\nrunning (0m39.0s), 1/1 VUs, 0 complete and 0 interrupted iterations\n1-user   [   0% ] 1 VUs  0m39.0s/1m0s  0/1 iters, 1 per VU\n\nrunning (0m40.0s), 1/1 VUs, 0 complete and 0 interrupted iterations\n1-user   [   0% ] 1 VUs  0m40.0s/1m0s  0/1 iters, 1 per VU\n\nrunning (0m41.0s), 1/1 VUs, 0 complete and 0 interrupted iterations\n1-user   [   0% ] 1 VUs  0m41.0s/1m0s  0/1 iters, 1 per VU\n\nrunning (0m42.0s), 1/1 VUs, 0 complete and 0 interrupted iterations\n1-user   [   0% ] 1 VUs  0m42.0s/1m0s  0/1 iters, 1 per VU\n\nrunning (0m43.0s), 1/1 VUs, 0 complete and 0 interrupted iterations\n1-user   [   0% ] 1 VUs  0m43.0s/1m0s  0/1 iters, 1 per VU\n\nrunning (0m44.0s), 1/1 VUs, 0 complete and 0 interrupted iterations\n1-user   [   0% ] 1 VUs  0m44.0s/1m0s  0/1 iters, 1 per VU\n\nrunning (0m45.0s), 1/1 VUs, 0 complete and 0 interrupted iterations\n1-user   [   0% ] 1 VUs  0m45.0s/1m0s  0/1 iters, 1 per VU\n\nrunning (0m45.0s), 0/1 VUs, 1 complete and 0 interrupted iterations\n1-user âœ“ [ 100% ] 1 VUs  0m45.0s/1m0s  1/1 iters, 1 per VU\n', 'stderr': 'time="2023-12-08T17:50:29Z" level=warning msg="Request Failed" error="Post \\"http://35.208.32.246:8000/inference\\": dial: i/o timeout"\n'}'
[36m[2023-12-08 17:50:45 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-12-08 17:50:45 INFO] [activity:215][39m Action: Run load testing
[36m[2023-12-08 17:50:45 DEBUG] [process:52][39m Running: /usr/bin/k6 run -o experimental-prometheus-rw load-testing.js
[36m[2023-12-08 17:52:52 DEBUG] [__init__:149][39m Data encoding detected as 'utf-8' with a confidence of 1.0
[36m[2023-12-08 17:52:52 DEBUG] [__init__:149][39m Data encoding detected as 'ascii' with a confidence of 1.0
[36m[2023-12-08 17:52:52 DEBUG] [activity:237][39m   => succeeded with '{'status': 0, 'stdout': '\n          /\\      |â€¾â€¾| /â€¾â€¾/   /â€¾â€¾/   \n     /\\  /  \\     |  |/  /   /  /    \n    /  \\/    \\    |     (   /   â€¾â€¾\\  \n   /          \\   |  |\\  \\ |  (â€¾)  | \n  / __________ \\  |__| \\__\\ \\_____/ .io\n\n  execution: local\n     script: load-testing.js\n     output: Prometheus remote write (http://localhost:9090/api/v1/write)\n\n  scenarios: (100.00%) 1 scenario, 16 max VUs, 1m30s max duration (incl. graceful stop):\n           * default: Up to 16 looping VUs for 1m0s over 1 stages (gracefulRampDown: 30s, gracefulStop: 30s)\n\n\nrunning (0m01.0s), 00/16 VUs, 0 complete and 0 interrupted iterations\ndefault   [   2% ] 00/16 VUs  0m01.0s/1m00.0s\n\nrunning (0m02.0s), 00/16 VUs, 0 complete and 0 interrupted iterations\ndefault   [   3% ] 00/16 VUs  0m02.0s/1m00.0s\n\nrunning (0m03.0s), 00/16 VUs, 0 complete and 0 interrupted iterations\ndefault   [   5% ] 00/16 VUs  0m03.0s/1m00.0s\n\nrunning (0m04.0s), 01/16 VUs, 0 complete and 0 interrupted iterations\ndefault   [   7% ] 01/16 VUs  0m04.0s/1m00.0s\n\nrunning (0m05.0s), 01/16 VUs, 0 complete and 0 interrupted iterations\ndefault   [   8% ] 01/16 VUs  0m05.0s/1m00.0s\n\nrunning (0m06.0s), 01/16 VUs, 0 complete and 0 interrupted iterations\ndefault   [  10% ] 01/16 VUs  0m06.0s/1m00.0s\n\nrunning (0m07.0s), 01/16 VUs, 0 complete and 0 interrupted iterations\ndefault   [  12% ] 01/16 VUs  0m07.0s/1m00.0s\n\nrunning (0m08.0s), 02/16 VUs, 0 complete and 0 interrupted iterations\ndefault   [  13% ] 02/16 VUs  0m08.0s/1m00.0s\n\nrunning (0m09.0s), 02/16 VUs, 0 complete and 0 interrupted iterations\ndefault   [  15% ] 02/16 VUs  0m09.0s/1m00.0s\n\nrunning (0m10.0s), 02/16 VUs, 0 complete and 0 interrupted iterations\ndefault   [  17% ] 02/16 VUs  0m10.0s/1m00.0s\n\nrunning (0m11.0s), 02/16 VUs, 0 complete and 0 interrupted iterations\ndefault   [  18% ] 02/16 VUs  0m11.0s/1m00.0s\n\nrunning (0m12.0s), 03/16 VUs, 0 complete and 0 interrupted iterations\ndefault   [  20% ] 03/16 VUs  0m12.0s/1m00.0s\n\nrunning (0m13.0s), 03/16 VUs, 0 complete and 0 interrupted iterations\ndefault   [  22% ] 03/16 VUs  0m13.0s/1m00.0s\n\nrunning (0m14.0s), 03/16 VUs, 0 complete and 0 interrupted iterations\ndefault   [  23% ] 03/16 VUs  0m14.0s/1m00.0s\n\nrunning (0m15.0s), 03/16 VUs, 0 complete and 0 interrupted iterations\ndefault   [  25% ] 03/16 VUs  0m15.0s/1m00.0s\n\nrunning (0m16.0s), 04/16 VUs, 0 complete and 0 interrupted iterations\ndefault   [  27% ] 04/16 VUs  0m16.0s/1m00.0s\n\nrunning (0m17.0s), 04/16 VUs, 0 complete and 0 interrupted iterations\ndefault   [  28% ] 04/16 VUs  0m17.0s/1m00.0s\n\nrunning (0m18.0s), 04/16 VUs, 0 complete and 0 interrupted iterations\ndefault   [  30% ] 04/16 VUs  0m18.0s/1m00.0s\n\nrunning (0m19.0s), 05/16 VUs, 0 complete and 0 interrupted iterations\ndefault   [  32% ] 05/16 VUs  0m19.0s/1m00.0s\n\nrunning (0m20.0s), 05/16 VUs, 0 complete and 0 interrupted iterations\ndefault   [  33% ] 05/16 VUs  0m20.0s/1m00.0s\n\nrunning (0m21.0s), 05/16 VUs, 0 complete and 0 interrupted iterations\ndefault   [  35% ] 05/16 VUs  0m21.0s/1m00.0s\n\nrunning (0m22.0s), 05/16 VUs, 0 complete and 0 interrupted iterations\ndefault   [  37% ] 05/16 VUs  0m22.0s/1m00.0s\n\nrunning (0m23.0s), 06/16 VUs, 0 complete and 0 interrupted iterations\ndefault   [  38% ] 06/16 VUs  0m23.0s/1m00.0s\n\nrunning (0m24.0s), 06/16 VUs, 0 complete and 0 interrupted iterations\ndefault   [  40% ] 06/16 VUs  0m24.0s/1m00.0s\n\nrunning (0m25.0s), 06/16 VUs, 0 complete and 0 interrupted iterations\ndefault   [  42% ] 06/16 VUs  0m25.0s/1m00.0s\n\nrunning (0m26.0s), 06/16 VUs, 0 complete and 0 interrupted iterations\ndefault   [  43% ] 06/16 VUs  0m26.0s/1m00.0s\n\nrunning (0m27.0s), 07/16 VUs, 0 complete and 0 interrupted iterations\ndefault   [  45% ] 07/16 VUs  0m27.0s/1m00.0s\n\nrunning (0m28.0s), 07/16 VUs, 0 complete and 0 interrupted iterations\ndefault   [  47% ] 07/16 VUs  0m28.0s/1m00.0s\n\nrunning (0m29.0s), 07/16 VUs, 0 complete and 0 interrupted iterations\ndefault   [  48% ] 07/16 VUs  0m29.0s/1m00.0s\n\nrunning (0m30.0s), 07/16 VUs, 0 complete and 0 interrupted iterations\ndefault   [  50% ] 07/16 VUs  0m30.0s/1m00.0s\n\nrunning (0m31.0s), 08/16 VUs, 0 complete and 0 interrupted iterations\ndefault   [  52% ] 08/16 VUs  0m31.0s/1m00.0s\n\nrunning (0m32.0s), 08/16 VUs, 0 complete and 0 interrupted iterations\ndefault   [  53% ] 08/16 VUs  0m32.0s/1m00.0s\n\nrunning (0m33.0s), 08/16 VUs, 0 complete and 0 interrupted iterations\ndefault   [  55% ] 08/16 VUs  0m33.0s/1m00.0s\n\nrunning (0m34.0s), 09/16 VUs, 0 complete and 0 interrupted iterations\ndefault   [  57% ] 09/16 VUs  0m34.0s/1m00.0s\n\nrunning (0m35.0s), 09/16 VUs, 0 complete and 0 interrupted iterations\ndefault   [  58% ] 09/16 VUs  0m35.0s/1m00.0s\n\nrunning (0m36.0s), 09/16 VUs, 0 complete and 0 interrupted iterations\ndefault   [  60% ] 09/16 VUs  0m36.0s/1m00.0s\n\nrunning (0m37.0s), 09/16 VUs, 0 complete and 0 interrupted iterations\ndefault   [  62% ] 09/16 VUs  0m37.0s/1m00.0s\n\nrunning (0m38.0s), 10/16 VUs, 0 complete and 0 interrupted iterations\ndefault   [  63% ] 10/16 VUs  0m38.0s/1m00.0s\n\nrunning (0m39.0s), 10/16 VUs, 0 complete and 0 interrupted iterations\ndefault   [  65% ] 10/16 VUs  0m39.0s/1m00.0s\n\nrunning (0m40.0s), 10/16 VUs, 0 complete and 0 interrupted iterations\ndefault   [  67% ] 10/16 VUs  0m40.0s/1m00.0s\n\nrunning (0m41.0s), 10/16 VUs, 0 complete and 0 interrupted iterations\ndefault   [  68% ] 10/16 VUs  0m41.0s/1m00.0s\n\nrunning (0m42.0s), 11/16 VUs, 0 complete and 0 interrupted iterations\ndefault   [  70% ] 11/16 VUs  0m42.0s/1m00.0s\n\nrunning (0m43.0s), 11/16 VUs, 0 complete and 0 interrupted iterations\ndefault   [  72% ] 11/16 VUs  0m43.0s/1m00.0s\n\nrunning (0m44.0s), 11/16 VUs, 0 complete and 0 interrupted iterations\ndefault   [  73% ] 11/16 VUs  0m44.0s/1m00.0s\n\nrunning (0m45.0s), 11/16 VUs, 0 complete and 0 interrupted iterations\ndefault   [  75% ] 11/16 VUs  0m45.0s/1m00.0s\n\nrunning (0m46.0s), 12/16 VUs, 0 complete and 0 interrupted iterations\ndefault   [  77% ] 12/16 VUs  0m46.0s/1m00.0s\n\nrunning (0m47.0s), 12/16 VUs, 0 complete and 0 interrupted iterations\ndefault   [  78% ] 12/16 VUs  0m47.0s/1m00.0s\n\nrunning (0m48.0s), 12/16 VUs, 0 complete and 0 interrupted iterations\ndefault   [  80% ] 12/16 VUs  0m48.0s/1m00.0s\n\nrunning (0m49.0s), 13/16 VUs, 1 complete and 0 interrupted iterations\ndefault   [  82% ] 13/16 VUs  0m49.0s/1m00.0s\n\nrunning (0m50.0s), 13/16 VUs, 1 complete and 0 interrupted iterations\ndefault   [  83% ] 13/16 VUs  0m50.0s/1m00.0s\n\nrunning (0m51.0s), 13/16 VUs, 1 complete and 0 interrupted iterations\ndefault   [  85% ] 13/16 VUs  0m51.0s/1m00.0s\n\nrunning (0m52.0s), 13/16 VUs, 1 complete and 0 interrupted iterations\ndefault   [  87% ] 13/16 VUs  0m52.0s/1m00.0s\n\nrunning (0m53.0s), 14/16 VUs, 2 complete and 0 interrupted iterations\ndefault   [  88% ] 14/16 VUs  0m53.0s/1m00.0s\n\nrunning (0m54.0s), 14/16 VUs, 2 complete and 0 interrupted iterations\ndefault   [  90% ] 14/16 VUs  0m54.0s/1m00.0s\n\nrunning (0m55.0s), 14/16 VUs, 2 complete and 0 interrupted iterations\ndefault   [  92% ] 14/16 VUs  0m55.0s/1m00.0s\n\nrunning (0m56.0s), 14/16 VUs, 2 complete and 0 interrupted iterations\ndefault   [  93% ] 14/16 VUs  0m56.0s/1m00.0s\n\nrunning (0m57.0s), 15/16 VUs, 3 complete and 0 interrupted iterations\ndefault   [  95% ] 15/16 VUs  0m57.0s/1m00.0s\n\nrunning (0m58.0s), 15/16 VUs, 3 complete and 0 interrupted iterations\ndefault   [  97% ] 15/16 VUs  0m58.0s/1m00.0s\n\nrunning (0m59.0s), 15/16 VUs, 3 complete and 0 interrupted iterations\ndefault   [  98% ] 15/16 VUs  0m59.0s/1m00.0s\n\nrunning (1m00.0s), 15/16 VUs, 3 complete and 0 interrupted iterations\ndefault   [ 100% ] 15/16 VUs  1m00.0s/1m00.0s\n\nrunning (1m01.0s), 14/16 VUs, 4 complete and 0 interrupted iterations\ndefault â†“ [ 100% ] 16/16 VUs  1m0s\n\nrunning (1m02.0s), 14/16 VUs, 4 complete and 0 interrupted iterations\ndefault â†“ [ 100% ] 16/16 VUs  1m0s\n\nrunning (1m03.0s), 14/16 VUs, 4 complete and 0 interrupted iterations\ndefault â†“ [ 100% ] 16/16 VUs  1m0s\n\nrunning (1m04.0s), 13/16 VUs, 5 complete and 0 interrupted iterations\ndefault â†“ [ 100% ] 16/16 VUs  1m0s\n\nrunning (1m05.0s), 13/16 VUs, 5 complete and 0 interrupted iterations\ndefault â†“ [ 100% ] 16/16 VUs  1m0s\n\nrunning (1m06.0s), 13/16 VUs, 5 complete and 0 interrupted iterations\ndefault â†“ [ 100% ] 16/16 VUs  1m0s\n\nrunning (1m07.0s), 13/16 VUs, 5 complete and 0 interrupted iterations\ndefault â†“ [ 100% ] 16/16 VUs  1m0s\n\nrunning (1m08.0s), 12/16 VUs, 6 complete and 0 interrupted iterations\ndefault â†“ [ 100% ] 16/16 VUs  1m0s\n\nrunning (1m09.0s), 12/16 VUs, 6 complete and 0 interrupted iterations\ndefault â†“ [ 100% ] 16/16 VUs  1m0s\n\nrunning (1m10.0s), 12/16 VUs, 6 complete and 0 interrupted iterations\ndefault â†“ [ 100% ] 16/16 VUs  1m0s\n\nrunning (1m11.0s), 12/16 VUs, 6 complete and 0 interrupted iterations\ndefault â†“ [ 100% ] 16/16 VUs  1m0s\n\nrunning (1m12.0s), 11/16 VUs, 7 complete and 0 interrupted iterations\ndefault â†“ [ 100% ] 16/16 VUs  1m0s\n\nrunning (1m13.0s), 11/16 VUs, 7 complete and 0 interrupted iterations\ndefault â†“ [ 100% ] 16/16 VUs  1m0s\n\nrunning (1m14.0s), 11/16 VUs, 7 complete and 0 interrupted iterations\ndefault â†“ [ 100% ] 16/16 VUs  1m0s\n\nrunning (1m15.0s), 11/16 VUs, 7 complete and 0 interrupted iterations\ndefault â†“ [ 100% ] 16/16 VUs  1m0s\n\nrunning (1m16.0s), 10/16 VUs, 8 complete and 0 interrupted iterations\ndefault â†“ [ 100% ] 16/16 VUs  1m0s\n\nrunning (1m17.0s), 10/16 VUs, 8 complete and 0 interrupted iterations\ndefault â†“ [ 100% ] 16/16 VUs  1m0s\n\nrunning (1m18.0s), 10/16 VUs, 8 complete and 0 interrupted iterations\ndefault â†“ [ 100% ] 16/16 VUs  1m0s\n\nrunning (1m19.0s), 09/16 VUs, 9 complete and 0 interrupted iterations\ndefault â†“ [ 100% ] 16/16 VUs  1m0s\n\nrunning (1m20.0s), 09/16 VUs, 9 complete and 0 interrupted iterations\ndefault â†“ [ 100% ] 16/16 VUs  1m0s\n\nrunning (1m21.0s), 09/16 VUs, 9 complete and 0 interrupted iterations\ndefault â†“ [ 100% ] 16/16 VUs  1m0s\n\nrunning (1m22.0s), 09/16 VUs, 9 complete and 0 interrupted iterations\ndefault â†“ [ 100% ] 16/16 VUs  1m0s\n\nrunning (1m23.0s), 08/16 VUs, 10 complete and 0 interrupted iterations\ndefault â†“ [ 100% ] 16/16 VUs  1m0s\n\nrunning (1m24.0s), 08/16 VUs, 10 complete and 0 interrupted iterations\ndefault â†“ [ 100% ] 16/16 VUs  1m0s\n\nrunning (1m25.0s), 08/16 VUs, 10 complete and 0 interrupted iterations\ndefault â†“ [ 100% ] 16/16 VUs  1m0s\n\nrunning (1m26.0s), 08/16 VUs, 10 complete and 0 interrupted iterations\ndefault â†“ [ 100% ] 16/16 VUs  1m0s\n\nrunning (1m27.0s), 07/16 VUs, 11 complete and 0 interrupted iterations\ndefault â†“ [ 100% ] 16/16 VUs  1m0s\n\nrunning (1m28.0s), 07/16 VUs, 11 complete and 0 interrupted iterations\ndefault â†“ [ 100% ] 16/16 VUs  1m0s\n\nrunning (1m29.0s), 07/16 VUs, 11 complete and 0 interrupted iterations\ndefault â†“ [ 100% ] 16/16 VUs  1m0s\n\nrunning (1m30.0s), 07/16 VUs, 11 complete and 0 interrupted iterations\ndefault â†“ [ 100% ] 16/16 VUs  1m0s\n\nrunning (1m30.0s), 00/16 VUs, 11 complete and 7 interrupted iterations\ndefault âœ“ [ 100% ] 07/16 VUs  1m0s\n', 'stderr': 'time="2023-12-08T17:51:54Z" level=warning msg="Request Failed" error="Post \\"http://35.208.32.246:8000/inference\\": dial: i/o timeout"\ntime="2023-12-08T17:51:58Z" level=warning msg="Request Failed" error="Post \\"http://35.208.32.246:8000/inference\\": dial: i/o timeout"\ntime="2023-12-08T17:52:02Z" level=warning msg="Request Failed" error="Post \\"http://35.208.32.246:8000/inference\\": dial: i/o timeout"\ntime="2023-12-08T17:52:05Z" level=warning msg="Request Failed" error="Post \\"http://35.208.32.246:8000/inference\\": dial: i/o timeout"\ntime="2023-12-08T17:52:09Z" level=warning msg="Request Failed" error="Post \\"http://35.208.32.246:8000/inference\\": dial: i/o timeout"\ntime="2023-12-08T17:52:13Z" level=warning msg="Request Failed" error="Post \\"http://35.208.32.246:8000/inference\\": dial: i/o timeout"\ntime="2023-12-08T17:52:17Z" level=warning msg="Request Failed" error="Post \\"http://35.208.32.246:8000/inference\\": dial: i/o timeout"\ntime="2023-12-08T17:52:20Z" level=warning msg="Request Failed" error="Post \\"http://35.208.32.246:8000/inference\\": dial: i/o timeout"\ntime="2023-12-08T17:52:24Z" level=warning msg="Request Failed" error="Post \\"http://35.208.32.246:8000/inference\\": dial: i/o timeout"\ntime="2023-12-08T17:52:28Z" level=warning msg="Request Failed" error="Post \\"http://35.208.32.246:8000/inference\\": dial: i/o timeout"\ntime="2023-12-08T17:52:32Z" level=warning msg="Request Failed" error="Post \\"http://35.208.32.246:8000/inference\\": dial: i/o timeout"\ntime="2023-12-08T17:52:35Z" level=warning msg="Request Failed" error="Post \\"http://35.208.32.246:8000/inference\\": dial: i/o timeout"\ntime="2023-12-08T17:52:39Z" level=warning msg="Request Failed" error="Post \\"http://35.208.32.246:8000/inference\\": dial: i/o timeout"\ntime="2023-12-08T17:52:39Z" level=warning msg="Request Failed" error="Post \\"http://35.208.32.246:8000/inference\\": dial: i/o timeout"\ntime="2023-12-08T17:52:43Z" level=warning msg="Request Failed" error="Post \\"http://35.208.32.246:8000/inference\\": dial: i/o timeout"\ntime="2023-12-08T17:52:43Z" level=warning msg="Request Failed" error="Post \\"http://35.208.32.246:8000/inference\\": dial: i/o timeout"\ntime="2023-12-08T17:52:47Z" level=warning msg="Request Failed" error="Post \\"http://35.208.32.246:8000/inference\\": dial: i/o timeout"\ntime="2023-12-08T17:52:47Z" level=warning msg="Request Failed" error="Post \\"http://35.208.32.246:8000/inference\\": dial: i/o timeout"\n'}'
[36m[2023-12-08 17:52:52 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[36m[2023-12-08 17:52:52 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-12-08 17:52:52 INFO] [activity:215][39m Action: Turn on interface VM on Google Cloud Platform
[36m[2023-12-08 17:52:52 DEBUG] [process:52][39m Running: /usr/bin/gcloud compute instances start --zone us-central1-a proxy-interaface
[36m[2023-12-08 17:53:06 DEBUG] [__init__:149][39m Data encoding detected as 'utf-8' with a confidence of 1.0
[36m[2023-12-08 17:53:07 DEBUG] [__init__:149][39m Data encoding detected as 'ascii' with a confidence of 1.0
[36m[2023-12-08 17:53:07 DEBUG] [activity:237][39m   => succeeded with '{'status': 0, 'stdout': '', 'stderr': 'Starting instance(s) proxy-interaface...\n..............................................done.\nUpdated [https://compute.googleapis.com/compute/v1/projects/mlops-398205/zones/us-central1-a/instances/proxy-interaface].\nInstance internal IP is 10.128.0.14\nInstance external IP is 35.208.32.246\n'}'
[32m[2023-12-08 17:53:07 INFO] [activity:257][39m Pausing after activity for 60s...
[36m[2023-12-08 17:54:07 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[36m[2023-12-08 17:54:07 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-12-08 17:54:07 INFO] [activity:215][39m Action: Turn on docker instance
[36m[2023-12-08 17:54:07 DEBUG] [process:52][39m Running: /usr/bin/ssh -i gcp-ta-key muhammad_haqqi01@35.208.32.246 sudo docker container start interface_proxy_1
[33m[2023-12-08 17:54:08 WARNING] [process:70][39m This process returned a non-zero exit code. This may indicate some error and not what you expected. Please have a look at the logs.
[36m[2023-12-08 17:54:08 DEBUG] [__init__:149][39m Data encoding detected as 'utf-8' with a confidence of 1.0
[36m[2023-12-08 17:54:08 DEBUG] [__init__:149][39m Data encoding detected as 'ascii' with a confidence of 1.0
[36m[2023-12-08 17:54:08 DEBUG] [activity:237][39m   => succeeded with '{'status': 255, 'stdout': '', 'stderr': '@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@\r\n@         WARNING: UNPROTECTED PRIVATE KEY FILE!          @\r\n@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@\r\nPermissions 0644 for \'gcp-ta-key\' are too open.\r\nIt is required that your private key files are NOT accessible by others.\r\nThis private key will be ignored.\r\nLoad key "gcp-ta-key": bad permissions\r\nmuhammad_haqqi01@35.208.32.246: Permission denied (publickey).\r\n'}'
[36m[2023-12-08 17:54:08 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[36m[2023-12-08 17:54:08 DEBUG] [__init__:445][39m No controls to apply on 'method'
[32m[2023-12-08 17:54:08 INFO] [run:966][39m Let's rollback...
[36m[2023-12-08 17:54:08 DEBUG] [__init__:445][39m No controls to apply on 'rollback'
[32m[2023-12-08 17:54:08 INFO] [rollback:32][39m No declared rollbacks, let's move on.
[36m[2023-12-08 17:54:08 DEBUG] [__init__:445][39m No controls to apply on 'rollback'
[32m[2023-12-08 17:54:08 INFO] [run:515][39m Experiment ended with status: completed
[36m[2023-12-08 17:54:08 DEBUG] [__init__:445][39m No controls to apply on 'experiment'
[36m[2023-12-08 17:54:08 DEBUG] [__init__:98][39m Cleaning up controls
[36m[2023-12-08 17:54:08 DEBUG] [__init__:107][39m Cleaning up control 'Change CHAOS_TYPE env value to off-interface'
[36m[2023-12-08 17:54:08 DEBUG] [caching:42][39m Clearing activities cache
[36m[2023-12-08 17:54:11 DEBUG] [cli:114][39m ###############################################################################
[36m[2023-12-08 17:54:11 DEBUG] [cli:115][39m Running command 'run'
[36m[2023-12-08 17:54:11 DEBUG] [cli:119][39m Using settings file '/root/.chaostoolkit/settings.yaml'
[36m[2023-12-08 17:54:12 DEBUG] [settings:30][39m The Chaos Toolkit settings file could not be found at '/root/.chaostoolkit/settings.yaml'.
[36m[2023-12-08 17:54:12 DEBUG] [__init__:445][39m No controls to apply on 'loader'
[36m[2023-12-08 17:54:12 DEBUG] [__init__:445][39m No controls to apply on 'loader'
[36m[2023-12-08 17:54:12 DEBUG] [caching:24][39m Building activity cache...
[36m[2023-12-08 17:54:12 DEBUG] [caching:35][39m Cached 8 activities
[32m[2023-12-08 17:54:12 INFO] [experiment:58][39m Validating the experiment's syntax
[36m[2023-12-08 17:54:12 DEBUG] [configuration:63][39m Loading configuration...
[36m[2023-12-08 17:54:12 DEBUG] [secret:78][39m Loading secrets...
[36m[2023-12-08 17:54:12 DEBUG] [secret:103][39m Done loading secrets
[32m[2023-12-08 17:54:12 INFO] [experiment:109][39m Experiment looks valid
[36m[2023-12-08 17:54:12 DEBUG] [caching:42][39m Clearing activities cache
[36m[2023-12-08 17:54:12 DEBUG] [cli:314][39m Runtime strategies: hypothesis - before-method-only / rollbacks - default
[36m[2023-12-08 17:54:12 DEBUG] [caching:24][39m Building activity cache...
[36m[2023-12-08 17:54:12 DEBUG] [caching:35][39m Cached 8 activities
[36m[2023-12-08 17:54:12 DEBUG] [configuration:63][39m Loading configuration...
[36m[2023-12-08 17:54:12 DEBUG] [secret:78][39m Loading secrets...
[36m[2023-12-08 17:54:12 DEBUG] [secret:103][39m Done loading secrets
[36m[2023-12-08 17:54:12 DEBUG] [configuration:160][39m Loading dynamic configuration...
[32m[2023-12-08 17:54:12 INFO] [run:369][39m Running experiment: Chaos Offline ML Inference Server Experiment
[36m[2023-12-08 17:54:12 DEBUG] [__init__:59][39m Initializing controls
[36m[2023-12-08 17:54:12 DEBUG] [__init__:68][39m Initializing control 'Change CHAOS_TYPE env value to off-interface'
[36m[2023-12-08 17:54:12 DEBUG] [__init__:68][39m Initializing control 'Change CHAOS_TYPE env value to off-inference'
[32m[2023-12-08 17:54:12 INFO] [run:396][39m Steady-state strategy: before-method-only
[32m[2023-12-08 17:54:12 INFO] [run:400][39m Rollbacks strategy: default
[36m[2023-12-08 17:54:12 DEBUG] [__init__:445][39m No controls to apply on 'experiment'
[36m[2023-12-08 17:54:12 DEBUG] [run:563][39m Running steady-state hypothesis before the method
[32m[2023-12-08 17:54:12 INFO] [hypothesis:186][39m Steady state hypothesis: Make sure that load testing has been done & able to prompt every types to server
[36m[2023-12-08 17:54:12 DEBUG] [__init__:445][39m No controls to apply on 'hypothesis'
[36m[2023-12-08 17:54:12 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-12-08 17:54:12 INFO] [activity:215][39m Probe: Normal load success rate testing log must exists
[36m[2023-12-08 17:54:12 DEBUG] [python:33][39m Activity 'Normal load success rate testing log must exists' loaded from '/usr/lib/python3.10/genericpath.py'
[36m[2023-12-08 17:54:12 DEBUG] [activity:237][39m   => succeeded with 'True'
[36m[2023-12-08 17:54:12 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[36m[2023-12-08 17:54:12 DEBUG] [hypothesis:228][39m allowed tolerance is True
[36m[2023-12-08 17:54:12 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-12-08 17:54:12 INFO] [activity:215][39m Probe: Normal load testing log must exists
[36m[2023-12-08 17:54:12 DEBUG] [python:33][39m Activity 'Normal load testing log must exists' loaded from '/usr/lib/python3.10/genericpath.py'
[36m[2023-12-08 17:54:12 DEBUG] [activity:237][39m   => succeeded with 'True'
[36m[2023-12-08 17:54:12 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[36m[2023-12-08 17:54:12 DEBUG] [hypothesis:228][39m allowed tolerance is True
[36m[2023-12-08 17:54:12 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-12-08 17:54:12 INFO] [activity:215][39m Probe: We can request text
[36m[2023-12-08 17:54:32 DEBUG] [activity:294][39m Activity failed
    Traceback (most recent call last):
      File "/root/tamlops/testing/env/lib/python3.10/site-packages/urllib3/connection.py", line 203, in _new_conn
        sock = connection.create_connection(
      File "/root/tamlops/testing/env/lib/python3.10/site-packages/urllib3/util/connection.py", line 85, in create_connection
        raise err
      File "/root/tamlops/testing/env/lib/python3.10/site-packages/urllib3/util/connection.py", line 73, in create_connection
        sock.connect(sa)
    TimeoutError: timed out
    
    The above exception was the direct cause of the following exception:
    
    Traceback (most recent call last):
      File "/root/tamlops/testing/env/lib/python3.10/site-packages/urllib3/connectionpool.py", line 790, in urlopen
        response = self._make_request(
      File "/root/tamlops/testing/env/lib/python3.10/site-packages/urllib3/connectionpool.py", line 496, in _make_request
        conn.request(
      File "/root/tamlops/testing/env/lib/python3.10/site-packages/urllib3/connection.py", line 395, in request
        self.endheaders()
      File "/usr/lib/python3.10/http/client.py", line 1278, in endheaders
        self._send_output(message_body, encode_chunked=encode_chunked)
      File "/usr/lib/python3.10/http/client.py", line 1038, in _send_output
        self.send(msg)
      File "/usr/lib/python3.10/http/client.py", line 976, in send
        self.connect()
      File "/root/tamlops/testing/env/lib/python3.10/site-packages/urllib3/connection.py", line 243, in connect
        self.sock = self._new_conn()
      File "/root/tamlops/testing/env/lib/python3.10/site-packages/urllib3/connection.py", line 212, in _new_conn
        raise ConnectTimeoutError(
    urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPConnection object at 0x7f807f234b20>, 'Connection to 35.208.32.246 timed out. (connect timeout=20)')
    
    The above exception was the direct cause of the following exception:
    
    Traceback (most recent call last):
      File "/root/tamlops/testing/env/lib/python3.10/site-packages/requests/adapters.py", line 486, in send
        resp = conn.urlopen(
      File "/root/tamlops/testing/env/lib/python3.10/site-packages/urllib3/connectionpool.py", line 844, in urlopen
        retries = retries.increment(
      File "/root/tamlops/testing/env/lib/python3.10/site-packages/urllib3/util/retry.py", line 515, in increment
        raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='35.208.32.246', port=8000): Max retries exceeded with url: /inference (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f807f234b20>, 'Connection to 35.208.32.246 timed out. (connect timeout=20)'))
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/root/tamlops/testing/env/lib/python3.10/site-packages/chaoslib/provider/http.py", line 59, in run_http_activity
        r = s.request(
      File "/root/tamlops/testing/env/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
        resp = self.send(prep, **send_kwargs)
      File "/root/tamlops/testing/env/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
        r = adapter.send(request, **kwargs)
      File "/root/tamlops/testing/env/lib/python3.10/site-packages/requests/adapters.py", line 507, in send
        raise ConnectTimeout(e, request=request)
    requests.exceptions.ConnectTimeout: HTTPConnectionPool(host='35.208.32.246', port=8000): Max retries exceeded with url: /inference (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f807f234b20>, 'Connection to 35.208.32.246 timed out. (connect timeout=20)'))
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/root/tamlops/testing/env/lib/python3.10/site-packages/chaoslib/activity.py", line 291, in run_activity
        result = run_http_activity(activity, configuration, secrets)
      File "/root/tamlops/testing/env/lib/python3.10/site-packages/chaoslib/provider/http.py", line 96, in run_http_activity
        raise ActivityFailed(f"failed to connect to {url}: {str(cex)}")
    chaoslib.exceptions.ActivityFailed: failed to connect to http://35.208.32.246:8000/inference: HTTPConnectionPool(host='35.208.32.246', port=8000): Max retries exceeded with url: /inference (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f807f234b20>, 'Connection to 35.208.32.246 timed out. (connect timeout=20)'))
[31m[2023-12-08 17:54:32 ERROR] [activity:245][39m   => failed: failed to connect to http://35.208.32.246:8000/inference: HTTPConnectionPool(host='35.208.32.246', port=8000): Max retries exceeded with url: /inference (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f807f234b20>, 'Connection to 35.208.32.246 timed out. (connect timeout=20)'))
[36m[2023-12-08 17:54:32 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[33m[2023-12-08 17:54:32 WARNING] [hypothesis:213][39m Probe terminated unexpectedly, so its tolerance could not be validated
[36m[2023-12-08 17:54:32 DEBUG] [__init__:445][39m No controls to apply on 'hypothesis'
[31m[2023-12-08 17:54:32 CRITICAL] [run:579][39m Steady state probe 'We can request text' is not in the given tolerance so failing this experiment
[32m[2023-12-08 17:54:32 INFO] [run:515][39m Experiment ended with status: failed
[36m[2023-12-08 17:54:32 DEBUG] [__init__:445][39m No controls to apply on 'experiment'
[36m[2023-12-08 17:54:32 DEBUG] [__init__:98][39m Cleaning up controls
[36m[2023-12-08 17:54:32 DEBUG] [__init__:107][39m Cleaning up control 'Change CHAOS_TYPE env value to off-interface'
[36m[2023-12-08 17:54:32 DEBUG] [__init__:107][39m Cleaning up control 'Change CHAOS_TYPE env value to off-inference'
[36m[2023-12-08 17:54:32 DEBUG] [caching:42][39m Clearing activities cache
[36m[2023-12-08 17:54:35 DEBUG] [cli:114][39m ###############################################################################
[36m[2023-12-08 17:54:35 DEBUG] [cli:115][39m Running command 'run'
[36m[2023-12-08 17:54:35 DEBUG] [cli:119][39m Using settings file '/root/.chaostoolkit/settings.yaml'
[36m[2023-12-08 17:54:37 DEBUG] [settings:30][39m The Chaos Toolkit settings file could not be found at '/root/.chaostoolkit/settings.yaml'.
[36m[2023-12-08 17:54:37 DEBUG] [__init__:445][39m No controls to apply on 'loader'
[36m[2023-12-08 17:54:37 DEBUG] [__init__:445][39m No controls to apply on 'loader'
[36m[2023-12-08 17:54:37 DEBUG] [caching:24][39m Building activity cache...
[36m[2023-12-08 17:54:37 DEBUG] [caching:35][39m Cached 8 activities
[32m[2023-12-08 17:54:37 INFO] [experiment:58][39m Validating the experiment's syntax
[36m[2023-12-08 17:54:37 DEBUG] [configuration:63][39m Loading configuration...
[36m[2023-12-08 17:54:37 DEBUG] [secret:78][39m Loading secrets...
[36m[2023-12-08 17:54:37 DEBUG] [secret:103][39m Done loading secrets
[32m[2023-12-08 17:54:37 INFO] [experiment:109][39m Experiment looks valid
[36m[2023-12-08 17:54:37 DEBUG] [caching:42][39m Clearing activities cache
[36m[2023-12-08 17:54:37 DEBUG] [cli:314][39m Runtime strategies: hypothesis - before-method-only / rollbacks - default
[36m[2023-12-08 17:54:37 DEBUG] [caching:24][39m Building activity cache...
[36m[2023-12-08 17:54:37 DEBUG] [caching:35][39m Cached 8 activities
[36m[2023-12-08 17:54:37 DEBUG] [configuration:63][39m Loading configuration...
[36m[2023-12-08 17:54:37 DEBUG] [secret:78][39m Loading secrets...
[36m[2023-12-08 17:54:37 DEBUG] [secret:103][39m Done loading secrets
[36m[2023-12-08 17:54:37 DEBUG] [configuration:160][39m Loading dynamic configuration...
[32m[2023-12-08 17:54:37 INFO] [run:369][39m Running experiment: Chaos Offline ML Training Server Experiment
[36m[2023-12-08 17:54:37 DEBUG] [__init__:59][39m Initializing controls
[36m[2023-12-08 17:54:37 DEBUG] [__init__:68][39m Initializing control 'Change CHAOS_TYPE env value to off-interface'
[32m[2023-12-08 17:54:37 INFO] [run:396][39m Steady-state strategy: before-method-only
[32m[2023-12-08 17:54:37 INFO] [run:400][39m Rollbacks strategy: default
[36m[2023-12-08 17:54:37 DEBUG] [__init__:445][39m No controls to apply on 'experiment'
[36m[2023-12-08 17:54:37 DEBUG] [run:563][39m Running steady-state hypothesis before the method
[32m[2023-12-08 17:54:37 INFO] [hypothesis:186][39m Steady state hypothesis: Make sure that load testing has been done & able to prompt every types to server
[36m[2023-12-08 17:54:37 DEBUG] [__init__:445][39m No controls to apply on 'hypothesis'
[36m[2023-12-08 17:54:37 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-12-08 17:54:37 INFO] [activity:215][39m Probe: Normal load success rate testing log must exists
[36m[2023-12-08 17:54:37 DEBUG] [python:33][39m Activity 'Normal load success rate testing log must exists' loaded from '/usr/lib/python3.10/genericpath.py'
[36m[2023-12-08 17:54:37 DEBUG] [activity:237][39m   => succeeded with 'True'
[36m[2023-12-08 17:54:37 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[36m[2023-12-08 17:54:37 DEBUG] [hypothesis:228][39m allowed tolerance is True
[36m[2023-12-08 17:54:37 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-12-08 17:54:37 INFO] [activity:215][39m Probe: Normal load testing log must exists
[36m[2023-12-08 17:54:37 DEBUG] [python:33][39m Activity 'Normal load testing log must exists' loaded from '/usr/lib/python3.10/genericpath.py'
[36m[2023-12-08 17:54:37 DEBUG] [activity:237][39m   => succeeded with 'True'
[36m[2023-12-08 17:54:37 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[36m[2023-12-08 17:54:37 DEBUG] [hypothesis:228][39m allowed tolerance is True
[36m[2023-12-08 17:54:37 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-12-08 17:54:37 INFO] [activity:215][39m Probe: We can request text
[36m[2023-12-08 17:54:57 DEBUG] [activity:294][39m Activity failed
    Traceback (most recent call last):
      File "/root/tamlops/testing/env/lib/python3.10/site-packages/urllib3/connection.py", line 203, in _new_conn
        sock = connection.create_connection(
      File "/root/tamlops/testing/env/lib/python3.10/site-packages/urllib3/util/connection.py", line 85, in create_connection
        raise err
      File "/root/tamlops/testing/env/lib/python3.10/site-packages/urllib3/util/connection.py", line 73, in create_connection
        sock.connect(sa)
    TimeoutError: timed out
    
    The above exception was the direct cause of the following exception:
    
    Traceback (most recent call last):
      File "/root/tamlops/testing/env/lib/python3.10/site-packages/urllib3/connectionpool.py", line 790, in urlopen
        response = self._make_request(
      File "/root/tamlops/testing/env/lib/python3.10/site-packages/urllib3/connectionpool.py", line 496, in _make_request
        conn.request(
      File "/root/tamlops/testing/env/lib/python3.10/site-packages/urllib3/connection.py", line 395, in request
        self.endheaders()
      File "/usr/lib/python3.10/http/client.py", line 1278, in endheaders
        self._send_output(message_body, encode_chunked=encode_chunked)
      File "/usr/lib/python3.10/http/client.py", line 1038, in _send_output
        self.send(msg)
      File "/usr/lib/python3.10/http/client.py", line 976, in send
        self.connect()
      File "/root/tamlops/testing/env/lib/python3.10/site-packages/urllib3/connection.py", line 243, in connect
        self.sock = self._new_conn()
      File "/root/tamlops/testing/env/lib/python3.10/site-packages/urllib3/connection.py", line 212, in _new_conn
        raise ConnectTimeoutError(
    urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPConnection object at 0x7fc541164b20>, 'Connection to 35.208.32.246 timed out. (connect timeout=20)')
    
    The above exception was the direct cause of the following exception:
    
    Traceback (most recent call last):
      File "/root/tamlops/testing/env/lib/python3.10/site-packages/requests/adapters.py", line 486, in send
        resp = conn.urlopen(
      File "/root/tamlops/testing/env/lib/python3.10/site-packages/urllib3/connectionpool.py", line 844, in urlopen
        retries = retries.increment(
      File "/root/tamlops/testing/env/lib/python3.10/site-packages/urllib3/util/retry.py", line 515, in increment
        raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='35.208.32.246', port=8000): Max retries exceeded with url: /inference (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fc541164b20>, 'Connection to 35.208.32.246 timed out. (connect timeout=20)'))
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/root/tamlops/testing/env/lib/python3.10/site-packages/chaoslib/provider/http.py", line 59, in run_http_activity
        r = s.request(
      File "/root/tamlops/testing/env/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
        resp = self.send(prep, **send_kwargs)
      File "/root/tamlops/testing/env/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
        r = adapter.send(request, **kwargs)
      File "/root/tamlops/testing/env/lib/python3.10/site-packages/requests/adapters.py", line 507, in send
        raise ConnectTimeout(e, request=request)
    requests.exceptions.ConnectTimeout: HTTPConnectionPool(host='35.208.32.246', port=8000): Max retries exceeded with url: /inference (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fc541164b20>, 'Connection to 35.208.32.246 timed out. (connect timeout=20)'))
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/root/tamlops/testing/env/lib/python3.10/site-packages/chaoslib/activity.py", line 291, in run_activity
        result = run_http_activity(activity, configuration, secrets)
      File "/root/tamlops/testing/env/lib/python3.10/site-packages/chaoslib/provider/http.py", line 96, in run_http_activity
        raise ActivityFailed(f"failed to connect to {url}: {str(cex)}")
    chaoslib.exceptions.ActivityFailed: failed to connect to http://35.208.32.246:8000/inference: HTTPConnectionPool(host='35.208.32.246', port=8000): Max retries exceeded with url: /inference (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fc541164b20>, 'Connection to 35.208.32.246 timed out. (connect timeout=20)'))
[31m[2023-12-08 17:54:57 ERROR] [activity:245][39m   => failed: failed to connect to http://35.208.32.246:8000/inference: HTTPConnectionPool(host='35.208.32.246', port=8000): Max retries exceeded with url: /inference (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fc541164b20>, 'Connection to 35.208.32.246 timed out. (connect timeout=20)'))
[36m[2023-12-08 17:54:57 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[33m[2023-12-08 17:54:57 WARNING] [hypothesis:213][39m Probe terminated unexpectedly, so its tolerance could not be validated
[36m[2023-12-08 17:54:57 DEBUG] [__init__:445][39m No controls to apply on 'hypothesis'
[31m[2023-12-08 17:54:57 CRITICAL] [run:579][39m Steady state probe 'We can request text' is not in the given tolerance so failing this experiment
[32m[2023-12-08 17:54:57 INFO] [run:515][39m Experiment ended with status: failed
[36m[2023-12-08 17:54:57 DEBUG] [__init__:445][39m No controls to apply on 'experiment'
[36m[2023-12-08 17:54:57 DEBUG] [__init__:98][39m Cleaning up controls
[36m[2023-12-08 17:54:57 DEBUG] [__init__:107][39m Cleaning up control 'Change CHAOS_TYPE env value to off-interface'
[36m[2023-12-08 17:54:57 DEBUG] [caching:42][39m Clearing activities cache
[36m[2023-12-08 17:54:59 DEBUG] [cli:114][39m ###############################################################################
[36m[2023-12-08 17:54:59 DEBUG] [cli:115][39m Running command 'report'
[36m[2023-12-08 17:54:59 DEBUG] [cli:119][39m Using settings file '/root/.chaostoolkit/settings.yaml'
[36m[2023-12-08 17:55:01 DEBUG] [configuration:63][39m Loading configuration...
[36m[2023-12-08 17:55:01 DEBUG] [secret:78][39m Loading secrets...
[36m[2023-12-08 17:55:01 DEBUG] [secret:103][39m Done loading secrets
[36m[2023-12-08 17:55:01 DEBUG] [caching:24][39m Building activity cache...
[36m[2023-12-08 17:55:01 DEBUG] [caching:35][39m Cached 9 activities
[36m[2023-12-08 17:55:02 DEBUG] [configuration:63][39m Loading configuration...
[36m[2023-12-08 17:55:02 DEBUG] [secret:78][39m Loading secrets...
[36m[2023-12-08 17:55:02 DEBUG] [secret:103][39m Done loading secrets
[36m[2023-12-08 17:55:02 DEBUG] [caching:24][39m Building activity cache...
[36m[2023-12-08 17:55:02 DEBUG] [caching:35][39m Cached 11 activities
